version: "2"
run:
  go: "1.21"
linters:
  enable:
    - contextcheck
    - godoclint
    - misspell
    - revive
    - godot
    - godox
    - modernize
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
    godoclint:
      default: all
    godot:
      period: true
      capital: false
      check-all: false
      exclude:
        - "^todo"
        - "^fixme"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - godoclint
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
